server:
  port: 8802

spring:
  application:
    name: rabbitmq
  # RabbitMQ 配置项，对应 RabbitProperties 配置类
  rabbitmq:
    host: 127.0.0.1 # RabbitMQ 服务的地址
    port: 5672 # RabbitMQ 服务的端口
    username: admin # RabbitMQ 服务的账号
    password: cjg260508119 # RabbitMQ 服务的密码

