server:
  port: 8866

spring:
  application:
    name: ribbonold



eureka:
  instance:
    prefer-ip-address: true  #配置是否显示ip地址,默认为false
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  #注册服务列表显示ip+端口
  client:
    # 跟上面一样，需要指向Eureka服务端地址，这样才能进行注册
    service-url:
      defaultZone: http://localhost:8761/eureka

#include的值也可以改成*，但建议还是最小暴露原则，用啥开启啥
management:
  endpoints:
    web:
      exposure:
        include: health,info,conditions,metrics,prometheus
#启用配置里的info开头的变量
  info:
    env:
      enabled: true

